plugins {
    id 'net.neoforged.gradle.userdev' version '7.0.170'
}

base {
    archivesName = "fku-neoforge-1.21.8"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

sourceSets {
    main {
        java {
            srcDir 'src/main/java'
            srcDir '../common/src/main/java'
        }
        resources {
            srcDir 'src/main/resources'
        }
    }
}

processResources {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"
}

jar {
    manifest {
        attributes([
            "Specification-Title": "fku",
            "Specification-Version": "1",
            "Implementation-Title": project.name,
            "Implementation-Version": project.jar.archiveVersion,
        ])
    }
}
