# This is an example mods.toml file for your mod.
modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="fku"
version="1.0.0"
displayName="FKU Mod"
logoFile="fku.png"
authors="Borneo099"
description="一个无敌吊炸天的mod"

# mixin 配置：声明 mixin 配置文件，使 FML 在加载时应用
[[mixins]]
config = "fku.mixins.json"
